In [3]:
!python -m pip install numpy



[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
!python.exe -m pip install --upgrade pip

^C


In [8]:
b = np.array([[[4,41],[8,81],[7,71]],[[3,1],[1,11],[5,51]],[[6,61],[9,91],[13,131]]])
print(b.shape)
#b[0:5:1,2]
#b[2:3]
b[1:]

(3, 3, 2)


array([[[  3,   1],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [25]:

a*3

array([[ 9, 24, 12],
       [27,  9, 15],
       [33, 45, 51],
       [57, 93, 24]])

In [37]:
print(a)

[[ 4  4  4]
 [ 4  4  4]
 [11 15 17]
 [19 31  8]]


In [42]:
a[0, :] = [1,2,3,]
print(a)

[[ 1  2  3]
 [ 4  4  4]
 [11 15 17]
 [19 31  8]]


In [47]:
a[:,1] = [52,61,25,78]
a

array([[ 1, 52,  3],
       [ 4, 61,  4],
       [11, 25, 17],
       [19, 78,  8]])

In [49]:
a[:2,1:] = [[201,202],[404,505]]
a

array([[  1, 201, 202],
       [  4, 404, 505],
       [ 11,  25,  17],
       [ 19,  78,   8]])

In [51]:
#np.append(a,[[1,1,1]], axis = 0)

array([[  1, 201, 202],
       [  4, 404, 505],
       [ 11,  25,  17],
       [ 19,  78,   8],
       [  1,   1,   1]])

In [65]:
np.append(a, [[12],[15],[16],[1]], axis = 1)


array([[  1, 201, 202,  12],
       [  4, 404, 505,  15],
       [ 11,  25,  17,  16],
       [ 19,  78,   8,   1]])

In [66]:
np.delete(a,1,0)

array([[  1, 201, 202],
       [ 11,  25,  17],
       [ 19,  78,   8]])

In [67]:
np.delete(a,1,1)

array([[  1, 202],
       [  4, 505],
       [ 11,  17],
       [ 19,   8]])

In [68]:
np.delete(a,3,axis=0)

array([[  1, 201, 202],
       [  4, 404, 505],
       [ 11,  25,  17]])

In [69]:
a.reshape(6,2)

array([[  1, 201],
       [202,   4],
       [404, 505],
       [ 11,  25],
       [ 17,  19],
       [ 78,   8]])

In [70]:
a.dtype

dtype('int32')

In [73]:
a1 = np.array([4.5,6,7])
a1

array([4.5, 6. , 7. ])

In [74]:
a1.dtype

dtype('float64')

In [75]:
a1.astype('uint16')

array([4, 6, 7], dtype=uint16)

In [78]:
a1.sum()

17.5

In [ ]:
#nutshell
## we create arrays
# 1. np.array()
# 2. np.ones()
# 3. np.zeros()
# 4. np.arange()
# 5. np.linspace()
# 6. np.random.randint()
#arrays have some functions and attributes 

In [7]:
import numpy as np

In [24]:
a = np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
#print(a.shape)
#print(a)
#a[0:5:1, 2]

array([ 4,  5, 17,  8])

In [2]:
pip install -U scikit-image

     ---------------------------------------- 0.0/23.7 MB ? eta -:--:--
     ---------------------------------------- 0.0/23.7 MB ? eta -:--:--
     ---------------------------------------- 0.1/23.7 MB 1.1 MB/s eta 0:00:22
     ---------------------------------------- 0.3/23.7 MB 1.7 MB/s eta 0:00:14
      --------------------------------------- 0.5/23.7 MB 2.2 MB/s eta 0:00:11
      --------------------------------------- 0.6/23.7 MB 2.3 MB/s eta 0:00:11
     - -------------------------------------- 0.7/23.7 MB 2.3 MB/s eta 0:00:10
     - -------------------------------------- 0.9/23.7 MB 2.5 MB/s eta 0:00:10
     - -------------------------------------- 1.1/23.7 MB 2.7 MB/s eta 0:00:09
     -- ------------------------------------- 1.3/23.7 MB 2.9 MB/s eta 0:00:08
     -- ------------------------------------- 1.5/23.7 MB 2.9 MB/s eta 0:00:08
     -- ------------------------------------- 1.6/23.7 MB 3.0 MB/s eta 0:00:08
     -- ------------------------------------- 1.7/23.7 MB 3.1 MB/s


[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import skimage