In [1]:
import numpy as np

In [2]:
#Create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#Create an array of 10 fives
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
#Create an array of integers from 10 to 51
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [5]:
#Create an array of even integers from 10 to 50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
#Create a 3x3 matrix with values ranging from 0 to 8
np.arange(9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
#Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#Use numpy to generate a random number between 0 and 1
np.random.rand(1)

array([0.95292944])

In [10]:
#Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution
np.random.randn(25)

array([-0.90273002,  0.18147511,  0.35487189, -0.71204341, -0.47068732,
       -0.30046097, -1.01794869, -1.1216385 ,  0.97268838,  0.7080893 ,
       -1.97868264, -1.50300897, -0.69738798,  1.54270811,  0.50008805,
       -0.44964821, -0.42439102,  0.70968772, -0.4133284 , -0.19899153,
        2.53224737, -0.47483655, -0.58917197, -1.63101881, -0.9691962 ])

In [ ]:
import skimage

^C


In [ ]:
!pip install matplotlib

In [14]:
np.arange(0.01,1.01,0.01).reshape((10,10)), sum(axis = 0)

TypeError: sum() takes at least 1 positional argument (0 given)

In [6]:
!pip install opencv-python

     -------------------------------------- 38.2/38.2 MB 867.1 kB/s eta 0:00:00



[notice] A new release of pip available: 22.3 -> 23.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
