In [1]:
import numpy as np


In [2]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.zeros((2,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.linspace(1,10,10, dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.random.randint(1,6,1)

array([4])

In [10]:
np.random.randint(1,6,[4,3,2])


array([[[4, 2],
        [2, 3],
        [4, 1]],

       [[1, 4],
        [1, 3],
        [1, 3]],

       [[3, 4],
        [2, 3],
        [1, 1]],

       [[1, 4],
        [5, 4],
        [4, 2]]])

In [11]:
np.random.randint(31,6000,[4,3])


array([[1916, 2368, 1649],
       [2399, 2019, 5452],
       [2835, 4454, 3076],
       [4895, 2191, 3794]])

In [12]:
np.random.seed(54)
np.random.randint(31,6000,[4,3],)

array([[ 929, 3886, 5174],
       [3840, 3423, 2096],
       [5160, 5669, 4744],
       [3350, 4835, 3347]])

In [13]:
np.random.rand(3,4)


array([[0.6714843 , 0.02965701, 0.39156203, 0.40479404],
       [0.18963101, 0.76710564, 0.61672315, 0.92627396],
       [0.32512403, 0.25315435, 0.72021792, 0.99695746]])

In [14]:
r = np.loadtxt('somedata.txt')

C:\Users\cp\AppData\Local\Temp\ipykernel_7880\4135997211.py:1: UserWarning: loadtxt: input contained no data: "somedata.txt"
  r = np.loadtxt('somedata.txt')


In [21]:
r = np.loadtxt('somedata.txt', dtype = str)
r

array(['Hi', 'my', 'name', 'is', 'Prerana', 'Sharma'], dtype='<U7')

In [23]:
p = np.random.rand(3,4)
p

array([[0.30787317, 0.17198668, 0.17538453, 0.16382659],
       [0.58501438, 0.47353556, 0.46075695, 0.23515401],
       [0.85621717, 0.47089378, 0.05458343, 0.99325708]])

In [27]:
np.savetxt('new.txt', p , delimiter = ',')

In [18]:
r = np.loadtxt('moredata.txt')
r

array([[45., 35., 56., 58.],
       [68., 89., 95., 26.]])

In [7]:
list(range(1,11,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]